### ISSUE TITLE
Failed to process view description: A pyldes:sequence_type property denoting the type of the tree:path view property is required.

### ISSUE THREAD

**Issue by xdxxxdx** [philippecarlo/pyldes#7]
Hello @philippecarlo,

By following the ([read me](https://github.com/philippecarlo/pyldes)). I am setting up the LDES Server

After posting the first collection. as described at ([read me](https://github.com/philippecarlo/pyldes)).
I got the error:
```
Traceback (most recent call last):
  File "/app/server.py", line 142, in post
    ldes_view = ldes_service.create_or_update_ldes_view(graph, collection_ref, view_descr_ref)
  File "/app/services/ldes_service.py", line 138, in create_or_update_ldes_view
    raise LdesServerError(f"A pyldes:sequence_type property denoting the type of the tree:path view property is required.")
tools.ldes_server_exception.LdesServerError: A pyldes:sequence_type property denoting the type of the tree:path view property is required.
```

The `sequence_type` cannot be properly initiated by the LDES example, 

Please have a look when you have time 
Thanks

**Comment by philippecarlo** [comment]
This should be solved. This was missing from the documentation. I fixed the example in the readme.
